chain_width = 60
disable_all_formatting = false
fn_params_layout = "Tall"
fn_call_width = 60
force_explicit_abi = true
hard_tabs = false
match_block_trailing_comma = true
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 10
single_line_if_else_max_width = 50
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = true # Fuchsia prefers the shortcut